apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd1 #' Soft affinity for ssd1
      # Note: This is a soft affinity, meaning the scheduler will try to place the pod'
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
