apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-with-init-container
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}

  initContainers:
    - name: busybox-container
      image: busybox:latest
      command: ['sh', '-c', 'echo Init container started; sleep 5']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx

  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80