kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: default 
spec:
  selector:
    app: backend-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30081
  type: NodePort
  
 