kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: default 
spec:
  selector:
    app: frontend-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30080
  type: NodePort
  
 